import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useEffect, useMemo, useState } from "react";

import { kiniColors } from "@/components/kini-ui";
import { getKiniDeviceIdentity } from "@/lib/kini-device";
import { trpc } from "@/lib/trpc";

function formatDate(value: Date | string) {
  return new Date(value).toLocaleString("vi-VN", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });
}

export function DeviceSessions() {
  const utils = trpc.useUtils();
  const sessions = trpc.sessions.list.useQuery();
  const revoke = trpc.sessions.revoke.useMutation({ onSuccess: () => void utils.sessions.list.invalidate() });
  const identifyCurrent = trpc.sessions.identifyCurrent.useMutation({ onSuccess: () => void utils.sessions.list.invalidate() });
  const [showHistory, setShowHistory] = useState(false);
  const askRevoke = (id: string, name: string) => Alert.alert("Đăng xuất thiết bị", `Bạn muốn thu hồi phiên của ${name}? Thiết bị này sẽ phải đăng nhập lại.`, [{ text: "Hủy", style: "cancel" }, { text: "Đăng xuất", style: "destructive", onPress: () => revoke.mutate({ sessionId: id }) }]);
  const { current, history } = useMemo(() => {
    const all = sessions.data ?? [];
    return { current: all.find((session) => !session.revokedAt) ?? null, history: all.filter((session) => Boolean(session.revokedAt)).slice(0, 5) };
  }, [sessions.data]);
  const currentDevice = getKiniDeviceIdentity();
  useEffect(() => {
    if (!current || identifyCurrent.isPending) return;
    if (current.deviceName === currentDevice.deviceName && current.platform === currentDevice.platform) return;
    identifyCurrent.mutate(currentDevice);
  }, [current?.id, current?.deviceName, current?.platform, currentDevice.deviceName, currentDevice.platform, identifyCurrent]);
  const iconFor = (platform: string) => platform === "web" ? "language" : platform === "ios" ? "phone-iphone" : "phone-android";
  return <View style={styles.section}><View style={styles.heading}><View><Text style={styles.title}>Thiết bị đăng nhập</Text><Text style={styles.subtitle}>KINI chỉ duy trì một thiết bị hoạt động tại một thời điểm.</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Làm mới danh sách thiết bị" onPress={() => void sessions.refetch()} style={styles.refresh}><MaterialIcons name="refresh" size={19} color={kiniColors.blue} /></TouchableOpacity></View>{sessions.isLoading ? <View style={styles.loading}><ActivityIndicator color={kiniColors.blue} /><Text style={styles.loadingText}>Đang tải thiết bị hiện tại…</Text></View> : current ? <View style={styles.list}><View style={[styles.row, styles.currentRow]}><View style={[styles.icon, styles.iconActive]}><MaterialIcons name={iconFor(current.platform)} size={22} color={kiniColors.blue} /></View><View style={styles.copy}><View style={styles.nameLine}><Text style={styles.name}>{current.deviceName}</Text><View style={[styles.status, styles.statusActive]}><Text style={[styles.statusText, styles.statusTextActive]}>Thiết bị này</Text></View></View><Text style={styles.meta}>Đang hoạt động từ {formatDate(current.lastActiveAt)}</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel={`Đăng xuất ${current.deviceName}`} onPress={() => askRevoke(current.id, current.deviceName)} style={styles.revoke}><MaterialIcons name="logout" size={18} color={kiniColors.coral} /></TouchableOpacity></View>{history.length ? <><TouchableOpacity accessibilityRole="button" accessibilityLabel="Xem lịch sử thiết bị" onPress={() => setShowHistory((value) => !value)} style={styles.historyToggle}><Text style={styles.historyToggleText}>{showHistory ? "Ẩn lịch sử đăng nhập" : `Xem ${history.length} phiên đã kết thúc`}</Text><MaterialIcons name={showHistory ? "expand-less" : "expand-more"} size={20} color={kiniColors.blue} /></TouchableOpacity>{showHistory ? history.map((session) => <View key={session.id} style={styles.row}><View style={styles.icon}><MaterialIcons name={iconFor(session.platform)} size={22} color={kiniColors.muted} /></View><View style={styles.copy}><View style={styles.nameLine}><Text style={styles.name}>{session.deviceName}</Text><View style={[styles.status, styles.statusClosed]}><Text style={[styles.statusText, styles.statusTextClosed]}>Đã kết thúc</Text></View></View><Text style={styles.meta}>Đã đăng xuất {formatDate(session.revokedAt!)}</Text></View></View>) : null}</> : null}</View> : <View style={styles.empty}><MaterialIcons name="devices" size={24} color={kiniColors.muted} /><Text style={styles.emptyText}>Chưa có thiết bị đang hoạt động.</Text></View>}</View>;
}

const styles = StyleSheet.create({ section: { marginTop: 26 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 9 }, title: { color: kiniColors.muted, fontSize: 13, fontWeight: "800" }, subtitle: { color: "#61758E", fontSize: 11, marginTop: 4 }, refresh: { width: 34, height: 34, borderRadius: 11, backgroundColor: kiniColors.mist, alignItems: "center", justifyContent: "center" }, list: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: kiniColors.line }, row: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: kiniColors.line }, currentRow: { backgroundColor: "#F5FAFF" }, icon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: kiniColors.cloud }, iconActive: { backgroundColor: kiniColors.mist }, copy: { flex: 1, gap: 4 }, nameLine: { flexDirection: "row", alignItems: "center", gap: 7 }, name: { color: kiniColors.navy, fontSize: 14, fontWeight: "800", flexShrink: 1 }, meta: { color: kiniColors.muted, fontSize: 11 }, status: { paddingHorizontal: 6, paddingVertical: 3, borderRadius: 7 }, statusActive: { backgroundColor: "#EAF8F1" }, statusClosed: { backgroundColor: kiniColors.cloud }, statusText: { fontSize: 9, fontWeight: "800" }, statusTextActive: { color: kiniColors.green }, statusTextClosed: { color: kiniColors.muted }, revoke: { width: 38, height: 38, borderRadius: 12, backgroundColor: "#FFF2F3", alignItems: "center", justifyContent: "center" }, historyToggle: { minHeight: 42, paddingHorizontal: 4, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, historyToggleText: { color: kiniColors.blue, fontSize: 12, fontWeight: "800" }, loading: { minHeight: 82, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: kiniColors.cloud, borderRadius: 15 }, loadingText: { color: kiniColors.muted, fontSize: 12 }, empty: { minHeight: 70, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: kiniColors.cloud, borderRadius: 15 }, emptyText: { color: kiniColors.muted, fontSize: 12 } });
