import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from "react-native";

import { kiniColors } from "@/components/kini-ui";
import { trpc } from "@/lib/trpc";

function formatDate(value: Date | string) {
  return new Date(value).toLocaleString("vi-VN", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });
}

export function DeviceSessions() {
  const utils = trpc.useUtils();
  const sessions = trpc.sessions.list.useQuery();
  const revoke = trpc.sessions.revoke.useMutation({ onSuccess: () => void utils.sessions.list.invalidate() });
  const askRevoke = (id: string, name: string) => Alert.alert("Đăng xuất thiết bị", `Bạn muốn thu hồi phiên của ${name}? Thiết bị này sẽ phải đăng nhập lại.`, [{ text: "Hủy", style: "cancel" }, { text: "Đăng xuất", style: "destructive", onPress: () => revoke.mutate({ sessionId: id }) }]);
  return <View style={styles.section}><View style={styles.heading}><View><Text style={styles.title}>Thiết bị đăng nhập</Text><Text style={styles.subtitle}>Đăng nhập mới sẽ tự vô hiệu hóa phiên cũ.</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Làm mới danh sách thiết bị" onPress={() => void sessions.refetch()} style={styles.refresh}><MaterialIcons name="refresh" size={19} color={kiniColors.blue} /></TouchableOpacity></View>{sessions.isLoading ? <View style={styles.loading}><ActivityIndicator color={kiniColors.blue} /><Text style={styles.loadingText}>Đang tải lịch sử thiết bị…</Text></View> : sessions.data?.length ? <View style={styles.list}>{sessions.data.map((session) => { const active = !session.revokedAt; return <View key={session.id} style={styles.row}><View style={[styles.icon, active && styles.iconActive]}><MaterialIcons name={session.platform === "web" ? "language" : session.platform === "ios" ? "phone-iphone" : "phone-android"} size={22} color={active ? kiniColors.blue : kiniColors.muted} /></View><View style={styles.copy}><View style={styles.nameLine}><Text style={styles.name}>{session.deviceName}</Text><View style={[styles.status, active ? styles.statusActive : styles.statusClosed]}><Text style={[styles.statusText, active ? styles.statusTextActive : styles.statusTextClosed]}>{active ? "Đang hoạt động" : "Đã kết thúc"}</Text></View></View><Text style={styles.meta}>{active ? `Hoạt động ${formatDate(session.lastActiveAt)}` : `Đã đăng xuất ${formatDate(session.revokedAt!)}`}</Text></View>{active ? <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Đăng xuất ${session.deviceName}`} onPress={() => askRevoke(session.id, session.deviceName)} style={styles.revoke}><MaterialIcons name="logout" size={18} color={kiniColors.coral} /></TouchableOpacity> : null}</View>; })}</View> : <View style={styles.empty}><MaterialIcons name="devices" size={24} color={kiniColors.muted} /><Text style={styles.emptyText}>Chưa có lịch sử thiết bị.</Text></View>}</View>;
}

const styles = StyleSheet.create({ section: { marginTop: 26 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 9 }, title: { color: kiniColors.muted, fontSize: 13, fontWeight: "800" }, subtitle: { color: "#9AA7B7", fontSize: 11, marginTop: 4 }, refresh: { width: 34, height: 34, borderRadius: 11, backgroundColor: kiniColors.mist, alignItems: "center", justifyContent: "center" }, list: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: kiniColors.line }, row: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: kiniColors.line }, icon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: kiniColors.cloud }, iconActive: { backgroundColor: kiniColors.mist }, copy: { flex: 1, gap: 4 }, nameLine: { flexDirection: "row", alignItems: "center", gap: 7 }, name: { color: kiniColors.navy, fontSize: 14, fontWeight: "800", flexShrink: 1 }, meta: { color: kiniColors.muted, fontSize: 11 }, status: { paddingHorizontal: 6, paddingVertical: 3, borderRadius: 7 }, statusActive: { backgroundColor: "#EAF8F1" }, statusClosed: { backgroundColor: kiniColors.cloud }, statusText: { fontSize: 9, fontWeight: "800" }, statusTextActive: { color: kiniColors.green }, statusTextClosed: { color: kiniColors.muted }, revoke: { width: 38, height: 38, borderRadius: 12, backgroundColor: "#FFF2F3", alignItems: "center", justifyContent: "center" }, loading: { minHeight: 82, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: kiniColors.cloud, borderRadius: 15 }, loadingText: { color: kiniColors.muted, fontSize: 12 }, empty: { minHeight: 70, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: kiniColors.cloud, borderRadius: 15 }, emptyText: { color: kiniColors.muted, fontSize: 12 } });
