import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

import { Avatar, kiniColors, PrimaryButton } from "@/components/kini-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

export default function ProfileScreen() {
  const { logout } = useAuth();
  const utils = trpc.useUtils();
  const profileQuery = trpc.profile.me.useQuery();
  const [editing, setEditing] = useState(false);
  const [username, setUsername] = useState("");
  const [displayName, setDisplayName] = useState("");
  const update = trpc.profile.update.useMutation({ onSuccess: async () => { await utils.profile.me.invalidate(); setEditing(false); }, onError: (error) => Alert.alert("Không thể lưu hồ sơ", error.message) });
  useEffect(() => { if (profileQuery.data) { setUsername(profileQuery.data.username); setDisplayName(profileQuery.data.displayName); if (profileQuery.data.username === `kini${profileQuery.data.userId}`) setEditing(true); } }, [profileQuery.data]);
  if (profileQuery.isLoading || !profileQuery.data) return <ScreenContainer><View style={styles.loading}><ActivityIndicator size="large" color={kiniColors.blue} /><Text style={styles.loadingText}>Đang tải hồ sơ KINI…</Text></View></ScreenContainer>;
  const profile = profileQuery.data;
  const save = () => update.mutate({ username: username.trim(), displayName: displayName.trim() });
  return <ScreenContainer><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Cá nhân</Text><View style={styles.verified}><MaterialIcons name="verified" size={17} color={kiniColors.green} /><Text style={styles.verifiedText}>Hồ sơ được xác thực qua tài khoản đăng nhập</Text></View><View style={styles.profileCard}><Avatar initials={profile.displayName.slice(0, 2).toUpperCase()} color={profile.avatarColor} size={64} /><View style={styles.profileCopy}><Text style={styles.name}>{profile.displayName}</Text><Text style={styles.handle}>@{profile.username}</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Chỉnh sửa hồ sơ" onPress={() => setEditing((value) => !value)} style={styles.edit}><MaterialIcons name="edit" size={18} color={kiniColors.blue} /></TouchableOpacity></View>{editing ? <View style={styles.editForm}><Text style={styles.formTitle}>Thiết lập KINI ID</Text><Text style={styles.formHint}>Bạn bè có thể tìm và gửi lời mời đến KINI ID này.</Text><TextInput value={displayName} onChangeText={setDisplayName} placeholder="Tên hiển thị" placeholderTextColor="#98A5B5" style={styles.input} /><TextInput value={username} onChangeText={setUsername} autoCapitalize="none" autoCorrect={false} placeholder="KINI ID, ví dụ: minh.nguyen" placeholderTextColor="#98A5B5" style={styles.input} /><PrimaryButton label={update.isPending ? "Đang lưu…" : "Lưu hồ sơ"} onPress={save} disabled={update.isPending} /></View> : null}<Text style={styles.section}>Bảo mật</Text><View style={styles.list}><View style={styles.row}><View style={styles.rowIcon}><MaterialIcons name="lock-outline" size={22} color={kiniColors.blue} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>Đăng nhập an toàn</Text><Text style={styles.rowSub}>Danh tính và phiên đăng nhập được bảo vệ bên ngoài KINI.</Text></View><MaterialIcons name="verified-user" size={20} color={kiniColors.green} /></View><View style={styles.row}><View style={styles.rowIcon}><MaterialIcons name="manage-accounts" size={22} color={kiniColors.blue} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>KINI ID</Text><Text style={styles.rowSub}>Dùng để tìm bạn bè và nhận lời mời kết bạn.</Text></View></View></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="Đăng xuất" onPress={() => void logout()} style={styles.signOut} activeOpacity={0.7}><MaterialIcons name="logout" size={20} color={kiniColors.coral} /><Text style={styles.signOutText}>Đăng xuất</Text></TouchableOpacity><Text style={styles.version}>KINI 1.1 · Tài khoản và tin nhắn đồng bộ</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 116 }, loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 }, loadingText: { color: kiniColors.muted, fontSize: 14 }, title: { color: kiniColors.navy, fontSize: 27, fontWeight: "900", marginTop: 2 }, verified: { marginTop: 13, flexDirection: "row", alignItems: "center", gap: 6 }, verifiedText: { color: kiniColors.green, fontSize: 12, fontWeight: "700" }, profileCard: { marginTop: 18, padding: 18, borderRadius: 22, backgroundColor: kiniColors.mist, alignItems: "center", flexDirection: "row", gap: 13 }, profileCopy: { flex: 1, gap: 4 }, name: { color: kiniColors.navy, fontSize: 17, fontWeight: "900" }, handle: { color: kiniColors.muted, fontSize: 13 }, edit: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: kiniColors.white }, editForm: { marginTop: 17, padding: 16, borderRadius: 18, backgroundColor: kiniColors.cloud, gap: 10 }, formTitle: { color: kiniColors.navy, fontSize: 16, fontWeight: "900" }, formHint: { color: kiniColors.muted, fontSize: 12, lineHeight: 18, marginBottom: 2 }, input: { height: 48, borderRadius: 13, paddingHorizontal: 14, backgroundColor: kiniColors.white, borderWidth: 1, borderColor: kiniColors.line, color: kiniColors.navy, fontSize: 15 }, section: { color: kiniColors.muted, fontSize: 13, fontWeight: "800", marginTop: 27, marginBottom: 9 }, list: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: kiniColors.line }, row: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: kiniColors.line }, rowIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: kiniColors.cloud }, rowCopy: { flex: 1, gap: 4 }, rowTitle: { color: kiniColors.navy, fontSize: 15, fontWeight: "800" }, rowSub: { color: kiniColors.muted, fontSize: 12, lineHeight: 17 }, signOut: { marginTop: 26, height: 50, borderRadius: 15, backgroundColor: "#FFF2F3", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, signOutText: { color: kiniColors.coral, fontSize: 15, fontWeight: "800" }, version: { color: "#A3AFBE", textAlign: "center", fontSize: 12, marginTop: 20 } });
